_config.yml

I have little to no clue/experience with adding apps, so let's see if it just works! ;)

ENH: add qsiprep

---

_config.yml

Attn @sajjadtorabian
Might want to wait for https://github.com/BIDS-Apps/PyMVPA/issues/2

ENH: Add PyMVPA bids-app from @sajjadtorabian

---

apps.md

Modified `version`, `issues` and `circleci` badges
- `apps.md`
**From Local Server**
Fix #2 and #19

fix badges for bids-apps

---

_config.yml

**Multiscalebrainparcellator**
github: https://github.com/sebastientourbier/multiscalebrainparcellator
dockerhub: https://hub.docker.com/r/sebastientourbier/multiscalebrainparcellator
**Connectome Mapper 3**
github: https://github.com/connectomicslab/connectomemapper3
dockerhub: https://hub.docker.com/r/sebastientourbier/connectomemapper-bidsapp

ENH: Add multiscalebrainparcellator and connectomemapper3 to BIDS-app listing

---

_config.yml

Add BIDSonym straight from Peer gh/dh

---

.circleci/config.yml
.github/workflows/artifact_redirector.yml

related to #46 ... I think we need to merge this first to trigger CircleCi. It would then need additional iterations in follow-up PRs.

CI: add circleci and circle redir GH action

---

about.md

remove poster file, it is now on zenodo

---

_includes/head.html
_includes/header.html
about.md
css/main.css
dev_faq.md

closes #51 
to be merged after #42

[DOC] update dev FAQ based on starter kit

---

LICENSE
_config.yml

Clarify license

---

_config.yml

@sappelhoff @Remi-Gau, Thanks for all your help to include TReNDS gift-bids, looking forward to see the continuation of further bids-apps...

add gift-bids

---

_config.yml

@sappelhoff @Remi-Gau . Should have read the comments, and finally it is correct! Thanks again!

mod2 gift-bids

---

.github/workflows/ruby_tests.yml
CONTRIBUTING.md
_config.yml
_includes/header.html
_posts/2016-01-08-welcome-to-jekyll.markdown
about.md
apps.md
css/uno.css
dev_faq.md
feed.xml
fonts/foundation-icons/foundation-icons.svg
images/BIDS_apps_logo_black.svg
sitemap.xml

following the progress made in https://github.com/bids-standard/bids-website/pull/241
- related: #46 
- related: #58
This just entails:
1. making a netlify account (I used the email address bids.maintenance@gmail.com)
2. associating it with a GitHub account (I used @bids-maintenance)
3. giving the permissions for an org and certain repos (org: bids-apps, repo: bids-apps.github.io)
4. starting the build
All just clicking around in browser windows, pretty much.

 Use Netlify to preview website builds in each PR

---

.github/ISSUE_TEMPLATE/bids_apps_submission.yml
.github/ISSUE_TEMPLATE/blank.md
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
CONTRIBUTING.md

- update contact email
- fix typo

[INFRA] Issue forms

---

Gemfile
_config.yml
apps.md

[ENH] update CI badges to accomodate several travis and github actions

---

apps.md

[ENH] add last commit badge

---

_config.yml

closes https://github.com/cpp-lln-lab/bidspm/issues/858
closes #81

[ENH] add bidspm

---

_config.yml

- closes #82 
- closes https://github.com/cpp-lln-lab/bidsMReye/issues/81

[ENH] add bidsmreye

---

_includes/app_subtable.html
_includes/app_table.html
_includes/table_row.html

closes #88 
- also refactor table code
- simplify app name displayed in table
- add a badge for docker image size
- rm badge for PR

[ENH] update app badges

---

_config.yml

[ENH] add fitlins

---

_includes/table_row.html

[FIX] fix docker badges

---

_config.yml

[ENH] add brainsuite

---

_config.yml

attn @zhao-cy  and @asmacdo please take over if there is more todo

Add pennlinc/toy_bids_app app

---

_config.yml

Changes proposed:
- Add an entry for ASLPrep to `_config.yml`.
- Update the datatype, branch, and testing for QSIPrep's entry.
- Remove `babs_tests`. I could add it back, but I'm not sure why it would be listed as a BIDS-App.

Add ASLPrep and update QSIPrep information

---

.github/workflows/validate.yml
.pre-commit-config.yaml
_config.yml
tools/create_dahsboard.py
tools/requirements.txt
tools/validate_apps.py

[ENH] validate docker hub url
